/**
 * // This file is auto-generated by the sd.config.cjs file.
 */

export const GlobalMedium = "5";
export const GlobalPaddingM = "25";
export const GlobalRed = "#bf0505";
export const GlobalBluGlobal = "#445cac";
export const NewBvn = "#988b8b";
export const NewBlueNew = "#18395e";