/**
 * // This file is auto-generated by the sd.config.cjs file.
 */

module.exports = {
  "light": {
    "medium": {
      "value": "5",
      "type": "borderRadius",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "5",
        "type": "borderRadius"
      },
      "name": "LightMedium",
      "attributes": {
        "category": "light",
        "type": "medium"
      },
      "path": [
        "light",
        "medium"
      ]
    },
    "globalWhite": {
      "value": "#fff",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#fff",
        "type": "color"
      },
      "name": "LightGlobalWhite",
      "attributes": {
        "category": "light",
        "type": "globalWhite"
      },
      "path": [
        "light",
        "globalWhite"
      ]
    },
    "globalBlack": {
      "value": "#000",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#000",
        "type": "color"
      },
      "name": "LightGlobalBlack",
      "attributes": {
        "category": "light",
        "type": "globalBlack"
      },
      "path": [
        "light",
        "globalBlack"
      ]
    },
    "goatPrimary": {
      "value": "#21edeb",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#21edeb",
        "type": "color"
      },
      "name": "LightGoatPrimary",
      "attributes": {
        "category": "light",
        "type": "goatPrimary"
      },
      "path": [
        "light",
        "goatPrimary"
      ]
    },
    "neutral400": {
      "value": "#D4D4D4",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#D4D4D4",
        "type": "color"
      },
      "name": "LightNeutral400",
      "attributes": {
        "category": "light",
        "type": "neutral400"
      },
      "path": [
        "light",
        "neutral400"
      ]
    },
    "warning400": {
      "value": "#A71010",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#A71010",
        "type": "color"
      },
      "name": "LightWarning400",
      "attributes": {
        "category": "light",
        "type": "warning400"
      },
      "path": [
        "light",
        "warning400"
      ]
    },
    "success": {
      "value": "#6DC2A9",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#6DC2A9",
        "type": "color"
      },
      "name": "LightSuccess",
      "attributes": {
        "category": "light",
        "type": "success"
      },
      "path": [
        "light",
        "success"
      ]
    },
    "supporting2": {
      "value": "#F437F8",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#F437F8",
        "type": "color"
      },
      "name": "LightSupporting2",
      "attributes": {
        "category": "light",
        "type": "supporting2"
      },
      "path": [
        "light",
        "supporting2"
      ]
    },
    "space0": {
      "value": "0",
      "type": "spacing",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "0",
        "type": "spacing"
      },
      "name": "LightSpace0",
      "attributes": {
        "category": "light",
        "type": "space0"
      },
      "path": [
        "light",
        "space0"
      ]
    },
    "space1": {
      "value": "4px",
      "type": "spacing",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "4px",
        "type": "spacing"
      },
      "name": "LightSpace1",
      "attributes": {
        "category": "light",
        "type": "space1"
      },
      "path": [
        "light",
        "space1"
      ]
    },
    "space2": {
      "value": "8px",
      "type": "spacing",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "8px",
        "type": "spacing"
      },
      "name": "LightSpace2",
      "attributes": {
        "category": "light",
        "type": "space2"
      },
      "path": [
        "light",
        "space2"
      ]
    },
    "space3": {
      "value": "16px",
      "type": "spacing",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "16px",
        "type": "spacing"
      },
      "name": "LightSpace3",
      "attributes": {
        "category": "light",
        "type": "space3"
      },
      "path": [
        "light",
        "space3"
      ]
    },
    "space9": {
      "value": "80px",
      "type": "spacing",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "80px",
        "type": "spacing"
      },
      "name": "LightSpace9",
      "attributes": {
        "category": "light",
        "type": "space9"
      },
      "path": [
        "light",
        "space9"
      ]
    },
    "fontSize0": {
      "value": "10px",
      "type": "fontSizes",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "10px",
        "type": "fontSizes"
      },
      "name": "LightFontSize0",
      "attributes": {
        "category": "light",
        "type": "fontSize0"
      },
      "path": [
        "light",
        "fontSize0"
      ]
    },
    "borderRadius3": {
      "value": "20px",
      "type": "borderRadius",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "20px",
        "type": "borderRadius"
      },
      "name": "LightBorderRadius3",
      "attributes": {
        "category": "light",
        "type": "borderRadius3"
      },
      "path": [
        "light",
        "borderRadius3"
      ]
    }
  },
  "dark": {
    "bvn": {
      "value": "#988b8b",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#988b8b",
        "type": "color"
      },
      "name": "DarkBvn",
      "attributes": {
        "category": "dark",
        "type": "bvn"
      },
      "path": [
        "dark",
        "bvn"
      ]
    },
    "blue new": {
      "value": "#18395e",
      "type": "color",
      "filePath": "sd-input/src/from-figma-tokens.json",
      "isSource": true,
      "original": {
        "value": "#18395e",
        "type": "color"
      },
      "name": "DarkBlueNew",
      "attributes": {
        "category": "dark",
        "type": "blue new"
      },
      "path": [
        "dark",
        "blue new"
      ]
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "light",
      "dark"
    ]
  }
};