/**
 * // This file is auto-generated by the sd.config.cjs file.
 */

export const TokenSetOrder0 = "global";
export const TokenSetOrder1 = "new";
export const Red = "#e70505";
export const Bvn = "#988b8b";
export const PrimaryBtn = "#9b27e6";
export const Medium = 5;
export const PaddingM = 25;