/**
 * // This file is auto-generated by the sd.config.cjs file.
 */

module.exports = {
  "Core": {
    "radii": {
      "0": {
        "value": "0",
        "type": "borderRadius",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "0",
          "type": "borderRadius"
        },
        "name": "CoreRadii0",
        "attributes": {
          "category": "Core",
          "type": "radii",
          "item": "0"
        },
        "path": [
          "Core",
          "radii",
          "0"
        ]
      },
      "1": {
        "value": "3px",
        "type": "borderRadius",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "3px",
          "type": "borderRadius"
        },
        "name": "CoreRadii1",
        "attributes": {
          "category": "Core",
          "type": "radii",
          "item": "1"
        },
        "path": [
          "Core",
          "radii",
          "1"
        ]
      },
      "2": {
        "value": "6px",
        "type": "borderRadius",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "6px",
          "type": "borderRadius"
        },
        "name": "CoreRadii2",
        "attributes": {
          "category": "Core",
          "type": "radii",
          "item": "2"
        },
        "path": [
          "Core",
          "radii",
          "2"
        ]
      },
      "3": {
        "value": "100px",
        "type": "borderRadius",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "100px",
          "type": "borderRadius"
        },
        "name": "CoreRadii3",
        "attributes": {
          "category": "Core",
          "type": "radii",
          "item": "3"
        },
        "path": [
          "Core",
          "radii",
          "3"
        ]
      }
    },
    "space": {
      "0": {
        "value": "0",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "0",
          "type": "spacing"
        },
        "name": "CoreSpace0",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "0"
        },
        "path": [
          "Core",
          "space",
          "0"
        ]
      },
      "1": {
        "value": "4px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "4px",
          "type": "spacing"
        },
        "name": "CoreSpace1",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "1"
        },
        "path": [
          "Core",
          "space",
          "1"
        ]
      },
      "2": {
        "value": "8px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "8px",
          "type": "spacing"
        },
        "name": "CoreSpace2",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "2"
        },
        "path": [
          "Core",
          "space",
          "2"
        ]
      },
      "3": {
        "value": "16px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "16px",
          "type": "spacing"
        },
        "name": "CoreSpace3",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "3"
        },
        "path": [
          "Core",
          "space",
          "3"
        ]
      },
      "4": {
        "value": "24px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "24px",
          "type": "spacing"
        },
        "name": "CoreSpace4",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "4"
        },
        "path": [
          "Core",
          "space",
          "4"
        ]
      },
      "5": {
        "value": "32px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "32px",
          "type": "spacing"
        },
        "name": "CoreSpace5",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "5"
        },
        "path": [
          "Core",
          "space",
          "5"
        ]
      },
      "6": {
        "value": "40px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "40px",
          "type": "spacing"
        },
        "name": "CoreSpace6",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "6"
        },
        "path": [
          "Core",
          "space",
          "6"
        ]
      },
      "7": {
        "value": "48px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "48px",
          "type": "spacing"
        },
        "name": "CoreSpace7",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "7"
        },
        "path": [
          "Core",
          "space",
          "7"
        ]
      },
      "8": {
        "value": "64px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "64px",
          "type": "spacing"
        },
        "name": "CoreSpace8",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "8"
        },
        "path": [
          "Core",
          "space",
          "8"
        ]
      },
      "9": {
        "value": "80px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "80px",
          "type": "spacing"
        },
        "name": "CoreSpace9",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "9"
        },
        "path": [
          "Core",
          "space",
          "9"
        ]
      },
      "10": {
        "value": "96px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "96px",
          "type": "spacing"
        },
        "name": "CoreSpace10",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "10"
        },
        "path": [
          "Core",
          "space",
          "10"
        ]
      },
      "11": {
        "value": "112px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "112px",
          "type": "spacing"
        },
        "name": "CoreSpace11",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "11"
        },
        "path": [
          "Core",
          "space",
          "11"
        ]
      },
      "12": {
        "value": "128px",
        "type": "spacing",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "128px",
          "type": "spacing"
        },
        "name": "CoreSpace12",
        "attributes": {
          "category": "Core",
          "type": "space",
          "item": "12"
        },
        "path": [
          "Core",
          "space",
          "12"
        ]
      }
    },
    "colors": {
      "global": {
        "white": {
          "value": "#ffffff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffffff",
            "type": "color"
          },
          "name": "CoreColorsGlobalWhite",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "global",
            "subitem": "white"
          },
          "path": [
            "Core",
            "colors",
            "global",
            "white"
          ]
        },
        "black": {
          "value": "#000000",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#000000",
            "type": "color"
          },
          "name": "CoreColorsGlobalBlack",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "global",
            "subitem": "black"
          },
          "path": [
            "Core",
            "colors",
            "global",
            "black"
          ]
        },
        "transparent": {
          "value": "#ffffff00",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffffff00",
            "type": "color"
          },
          "name": "CoreColorsGlobalTransparent",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "global",
            "subitem": "transparent"
          },
          "path": [
            "Core",
            "colors",
            "global",
            "transparent"
          ]
        }
      },
      "neutral": {
        "s100": {
          "value": "#fafafa",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#fafafa",
            "type": "color"
          },
          "name": "CoreColorsNeutralS100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s100"
          ]
        },
        "s200": {
          "value": "#f5f5f5",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#f5f5f5",
            "type": "color"
          },
          "name": "CoreColorsNeutralS200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s200"
          ]
        },
        "s300": {
          "value": "#e5e5e5",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#e5e5e5",
            "type": "color"
          },
          "name": "CoreColorsNeutralS300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s300"
          ]
        },
        "s400": {
          "value": "#d4d4d4",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#d4d4d4",
            "type": "color"
          },
          "name": "CoreColorsNeutralS400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s400"
          ]
        },
        "s500": {
          "value": "#a3a3a3",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#a3a3a3",
            "type": "color"
          },
          "name": "CoreColorsNeutralS500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s500"
          ]
        },
        "s600": {
          "value": "#737373",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#737373",
            "type": "color"
          },
          "name": "CoreColorsNeutralS600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s600"
          ]
        },
        "s700": {
          "value": "#525252",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#525252",
            "type": "color"
          },
          "name": "CoreColorsNeutralS700",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s700"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s700"
          ]
        },
        "s800": {
          "value": "#404040",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#404040",
            "type": "color"
          },
          "name": "CoreColorsNeutralS800",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s800"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s800"
          ]
        },
        "s900": {
          "value": "#353535",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#353535",
            "type": "color"
          },
          "name": "CoreColorsNeutralS900",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s900"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s900"
          ]
        },
        "s1000": {
          "value": "#171717",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#171717",
            "type": "color"
          },
          "name": "CoreColorsNeutralS1000",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "neutral",
            "subitem": "s1000"
          },
          "path": [
            "Core",
            "colors",
            "neutral",
            "s1000"
          ]
        }
      },
      "primary": {
        "s100": {
          "value": "#ffd5b8",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffd5b8",
            "type": "color"
          },
          "name": "CoreColorsPrimaryS100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "primary",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "primary",
            "s100"
          ]
        },
        "s200": {
          "value": "#ffb685",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffb685",
            "type": "color"
          },
          "name": "CoreColorsPrimaryS200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "primary",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "primary",
            "s200"
          ]
        },
        "s300": {
          "value": "#ff9d57",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ff9d57",
            "type": "color"
          },
          "name": "CoreColorsPrimaryS300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "primary",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "primary",
            "s300"
          ]
        },
        "s400": {
          "value": "#bd550a",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#bd550a",
            "type": "color"
          },
          "name": "CoreColorsPrimaryS400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "primary",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "primary",
            "s400"
          ]
        },
        "s500": {
          "value": "#8a3900",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#8a3900",
            "type": "color"
          },
          "name": "CoreColorsPrimaryS500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "primary",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "primary",
            "s500"
          ]
        },
        "s600": {
          "value": "#572400",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#572400",
            "type": "color"
          },
          "name": "CoreColorsPrimaryS600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "primary",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "primary",
            "s600"
          ]
        },
        "goat": {
          "value": "#ee7620",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ee7620",
            "type": "color"
          },
          "name": "CoreColorsPrimaryGoat",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "primary",
            "subitem": "goat"
          },
          "path": [
            "Core",
            "colors",
            "primary",
            "goat"
          ]
        }
      },
      "secondary": {
        "s100": {
          "value": "#ffe2b2",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffe2b2",
            "type": "color"
          },
          "name": "CoreColorsSecondaryS100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "secondary",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "secondary",
            "s100"
          ]
        },
        "s200": {
          "value": "#ffcc7a",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffcc7a",
            "type": "color"
          },
          "name": "CoreColorsSecondaryS200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "secondary",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "secondary",
            "s200"
          ]
        },
        "s300": {
          "value": "#ffb742",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffb742",
            "type": "color"
          },
          "name": "CoreColorsSecondaryS300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "secondary",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "secondary",
            "s300"
          ]
        },
        "s400": {
          "value": "#c27800",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#c27800",
            "type": "color"
          },
          "name": "CoreColorsSecondaryS400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "secondary",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "secondary",
            "s400"
          ]
        },
        "s500": {
          "value": "#8f5800",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#8f5800",
            "type": "color"
          },
          "name": "CoreColorsSecondaryS500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "secondary",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "secondary",
            "s500"
          ]
        },
        "s600": {
          "value": "#5c3900",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#5c3900",
            "type": "color"
          },
          "name": "CoreColorsSecondaryS600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "secondary",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "secondary",
            "s600"
          ]
        },
        "main": {
          "value": "#f59d0f",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#f59d0f",
            "type": "color"
          },
          "name": "CoreColorsSecondaryMain",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "secondary",
            "subitem": "main"
          },
          "path": [
            "Core",
            "colors",
            "secondary",
            "main"
          ]
        }
      },
      "Gradient": {
        "Orange > Amber - #EE7622 > #F59C0D": {
          "value": "linear-gradient(90deg, #ee7622 0%, #f6a705 100%)",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "linear-gradient(90deg, #ee7622 0%, #f6a705 100%)",
            "type": "color"
          },
          "name": "CoreColorsGradientOrangeAmberEe7622F59C0D",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "Gradient",
            "subitem": "Orange > Amber - #EE7622 > #F59C0D"
          },
          "path": [
            "Core",
            "colors",
            "Gradient",
            "Orange > Amber - #EE7622 > #F59C0D"
          ]
        },
        "Orange > Pink - #EE7620 > #F131BC": {
          "value": "linear-gradient(119deg, #ee7620 0%, #f131bc 100%)",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "linear-gradient(119deg, #ee7620 0%, #f131bc 100%)",
            "type": "color"
          },
          "name": "CoreColorsGradientOrangePinkEe7620F131Bc",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "Gradient",
            "subitem": "Orange > Pink - #EE7620 > #F131BC"
          },
          "path": [
            "Core",
            "colors",
            "Gradient",
            "Orange > Pink - #EE7620 > #F131BC"
          ]
        },
        "Orange > Pink > Purple - #F79426, #F131BC, #5212E4": {
          "value": "linear-gradient(90deg, #f79426 0%, #f131bc 42.35%, #5212e4 100%)",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "linear-gradient(90deg, #f79426 0%, #f131bc 42.35%, #5212e4 100%)",
            "type": "color"
          },
          "name": "CoreColorsGradientOrangePinkPurpleF79426F131Bc5212E4",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "Gradient",
            "subitem": "Orange > Pink > Purple - #F79426, #F131BC, #5212E4"
          },
          "path": [
            "Core",
            "colors",
            "Gradient",
            "Orange > Pink > Purple - #F79426, #F131BC, #5212E4"
          ]
        },
        "Neutral 6-9 - #737373 > #353535": {
          "value": "linear-gradient(90deg, #737373 0%, #353535 100%)",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "linear-gradient(90deg, #737373 0%, #353535 100%)",
            "type": "color"
          },
          "name": "CoreColorsGradientNeutral69737373353535",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "Gradient",
            "subitem": "Neutral 6-9 - #737373 > #353535"
          },
          "path": [
            "Core",
            "colors",
            "Gradient",
            "Neutral 6-9 - #737373 > #353535"
          ]
        },
        "Dark Grey": {
          "value": "linear-gradient(90deg, #414141 0%, #363636 100%)",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "linear-gradient(90deg, #414141 0%, #363636 100%)",
            "type": "color"
          },
          "name": "CoreColorsGradientDarkGrey",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "Gradient",
            "subitem": "Dark Grey"
          },
          "path": [
            "Core",
            "colors",
            "Gradient",
            "Dark Grey"
          ]
        }
      },
      "success": {
        "s100": {
          "value": "#d5fff2",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#d5fff2",
            "type": "color"
          },
          "name": "CoreColorsSuccessS100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "success",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "success",
            "s100"
          ]
        },
        "s200": {
          "value": "#b5ffe9",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#b5ffe9",
            "type": "color"
          },
          "name": "CoreColorsSuccessS200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "success",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "success",
            "s200"
          ]
        },
        "s300": {
          "value": "#95ffdf",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#95ffdf",
            "type": "color"
          },
          "name": "CoreColorsSuccessS300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "success",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "success",
            "s300"
          ]
        },
        "s400": {
          "value": "#79e1c2",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#79e1c2",
            "type": "color"
          },
          "name": "CoreColorsSuccessS400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "success",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "success",
            "s400"
          ]
        },
        "s500": {
          "value": "#409078",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#409078",
            "type": "color"
          },
          "name": "CoreColorsSuccessS500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "success",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "success",
            "s500"
          ]
        },
        "s600": {
          "value": "#296754",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#296754",
            "type": "color"
          },
          "name": "CoreColorsSuccessS600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "success",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "success",
            "s600"
          ]
        },
        "main": {
          "value": "#5bb99c",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#5bb99c",
            "type": "color"
          },
          "name": "CoreColorsSuccessMain",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "success",
            "subitem": "main"
          },
          "path": [
            "Core",
            "colors",
            "success",
            "main"
          ]
        }
      },
      "supporting1": {
        "s100": {
          "value": "#b7e1ff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#b7e1ff",
            "type": "color"
          },
          "name": "CoreColorsSupporting1S100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting1",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "supporting1",
            "s100"
          ]
        },
        "s200": {
          "value": "#85ccff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#85ccff",
            "type": "color"
          },
          "name": "CoreColorsSupporting1S200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting1",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "supporting1",
            "s200"
          ]
        },
        "s300": {
          "value": "#54b7ff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#54b7ff",
            "type": "color"
          },
          "name": "CoreColorsSupporting1S300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting1",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "supporting1",
            "s300"
          ]
        },
        "s400": {
          "value": "#0870bb",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#0870bb",
            "type": "color"
          },
          "name": "CoreColorsSupporting1S400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting1",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "supporting1",
            "s400"
          ]
        },
        "s500": {
          "value": "#004f88",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#004f88",
            "type": "color"
          },
          "name": "CoreColorsSupporting1S500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting1",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "supporting1",
            "s500"
          ]
        },
        "s600": {
          "value": "#003255",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#003255",
            "type": "color"
          },
          "name": "CoreColorsSupporting1S600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting1",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "supporting1",
            "s600"
          ]
        },
        "main": {
          "value": "#2098ee",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#2098ee",
            "type": "color"
          },
          "name": "CoreColorsSupporting1Main",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting1",
            "subitem": "main"
          },
          "path": [
            "Core",
            "colors",
            "supporting1",
            "main"
          ]
        }
      },
      "supporting2": {
        "s100": {
          "value": "#fdafff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#fdafff",
            "type": "color"
          },
          "name": "CoreColorsSupporting2S100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting2",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "supporting2",
            "s100"
          ]
        },
        "s200": {
          "value": "#fc74ff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#fc74ff",
            "type": "color"
          },
          "name": "CoreColorsSupporting2S200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting2",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "supporting2",
            "s200"
          ]
        },
        "s300": {
          "value": "#cb21cf",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#cb21cf",
            "type": "color"
          },
          "name": "CoreColorsSupporting2S300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting2",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "supporting2",
            "s300"
          ]
        },
        "s400": {
          "value": "#a310a6",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#a310a6",
            "type": "color"
          },
          "name": "CoreColorsSupporting2S400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting2",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "supporting2",
            "s400"
          ]
        },
        "s500": {
          "value": "#7b047d",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#7b047d",
            "type": "color"
          },
          "name": "CoreColorsSupporting2S500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting2",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "supporting2",
            "s500"
          ]
        },
        "s600": {
          "value": "#530054",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#530054",
            "type": "color"
          },
          "name": "CoreColorsSupporting2S600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting2",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "supporting2",
            "s600"
          ]
        },
        "main": {
          "value": "#f437f8",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#f437f8",
            "type": "color"
          },
          "name": "CoreColorsSupporting2Main",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting2",
            "subitem": "main"
          },
          "path": [
            "Core",
            "colors",
            "supporting2",
            "main"
          ]
        }
      },
      "supporting3": {
        "s100": {
          "value": "#d5b7ff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#d5b7ff",
            "type": "color"
          },
          "name": "CoreColorsSupporting3S100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting3",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "supporting3",
            "s100"
          ]
        },
        "s200": {
          "value": "#b885ff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#b885ff",
            "type": "color"
          },
          "name": "CoreColorsSupporting3S200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting3",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "supporting3",
            "s200"
          ]
        },
        "s300": {
          "value": "#9b54ff",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#9b54ff",
            "type": "color"
          },
          "name": "CoreColorsSupporting3S300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting3",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "supporting3",
            "s300"
          ]
        },
        "s400": {
          "value": "#5308bb",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#5308bb",
            "type": "color"
          },
          "name": "CoreColorsSupporting3S400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting3",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "supporting3",
            "s400"
          ]
        },
        "s500": {
          "value": "#390088",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#390088",
            "type": "color"
          },
          "name": "CoreColorsSupporting3S500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting3",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "supporting3",
            "s500"
          ]
        },
        "s600": {
          "value": "#240055",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#240055",
            "type": "color"
          },
          "name": "CoreColorsSupporting3S600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting3",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "supporting3",
            "s600"
          ]
        },
        "main": {
          "value": "#7620ee",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#7620ee",
            "type": "color"
          },
          "name": "CoreColorsSupporting3Main",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "supporting3",
            "subitem": "main"
          },
          "path": [
            "Core",
            "colors",
            "supporting3",
            "main"
          ]
        }
      },
      "destructive": {
        "s100": {
          "value": "#ffafaf",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ffafaf",
            "type": "color"
          },
          "name": "CoreColorsDestructiveS100",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "destructive",
            "subitem": "s100"
          },
          "path": [
            "Core",
            "colors",
            "destructive",
            "s100"
          ]
        },
        "s200": {
          "value": "#ff7474",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#ff7474",
            "type": "color"
          },
          "name": "CoreColorsDestructiveS200",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "destructive",
            "subitem": "s200"
          },
          "path": [
            "Core",
            "colors",
            "destructive",
            "s200"
          ]
        },
        "s300": {
          "value": "#f93737",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#f93737",
            "type": "color"
          },
          "name": "CoreColorsDestructiveS300",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "destructive",
            "subitem": "s300"
          },
          "path": [
            "Core",
            "colors",
            "destructive",
            "s300"
          ]
        },
        "s400": {
          "value": "#a71010",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#a71010",
            "type": "color"
          },
          "name": "CoreColorsDestructiveS400",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "destructive",
            "subitem": "s400"
          },
          "path": [
            "Core",
            "colors",
            "destructive",
            "s400"
          ]
        },
        "s500": {
          "value": "#7e0404",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#7e0404",
            "type": "color"
          },
          "name": "CoreColorsDestructiveS500",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "destructive",
            "subitem": "s500"
          },
          "path": [
            "Core",
            "colors",
            "destructive",
            "s500"
          ]
        },
        "s600": {
          "value": "#550000",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#550000",
            "type": "color"
          },
          "name": "CoreColorsDestructiveS600",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "destructive",
            "subitem": "s600"
          },
          "path": [
            "Core",
            "colors",
            "destructive",
            "s600"
          ]
        },
        "main": {
          "value": "#d02121",
          "type": "color",
          "filePath": "sd-input/src/from-figma-tokens.json",
          "isSource": true,
          "original": {
            "value": "#d02121",
            "type": "color"
          },
          "name": "CoreColorsDestructiveMain",
          "attributes": {
            "category": "Core",
            "type": "colors",
            "item": "destructive",
            "subitem": "main"
          },
          "path": [
            "Core",
            "colors",
            "destructive",
            "main"
          ]
        }
      }
    },
    "fontSize": {
      "0": {
        "value": "10px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "10px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize0",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "0"
        },
        "path": [
          "Core",
          "fontSize",
          "0"
        ]
      },
      "1": {
        "value": "12px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "12px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize1",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "1"
        },
        "path": [
          "Core",
          "fontSize",
          "1"
        ]
      },
      "2": {
        "value": "14px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "14px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize2",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "2"
        },
        "path": [
          "Core",
          "fontSize",
          "2"
        ]
      },
      "3": {
        "value": "16px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "16px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize3",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "3"
        },
        "path": [
          "Core",
          "fontSize",
          "3"
        ]
      },
      "4": {
        "value": "20px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "20px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize4",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "4"
        },
        "path": [
          "Core",
          "fontSize",
          "4"
        ]
      },
      "5": {
        "value": "24px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "24px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize5",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "5"
        },
        "path": [
          "Core",
          "fontSize",
          "5"
        ]
      },
      "6": {
        "value": "32px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "32px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize6",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "6"
        },
        "path": [
          "Core",
          "fontSize",
          "6"
        ]
      },
      "7": {
        "value": "40px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "40px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize7",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "7"
        },
        "path": [
          "Core",
          "fontSize",
          "7"
        ]
      },
      "8": {
        "value": "48px",
        "type": "fontSizes",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "48px",
          "type": "fontSizes"
        },
        "name": "CoreFontSize8",
        "attributes": {
          "category": "Core",
          "type": "fontSize",
          "item": "8"
        },
        "path": [
          "Core",
          "fontSize",
          "8"
        ]
      }
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "Core"
    ]
  }
};