/**
 * // This file is auto-generated by the sd.config.cjs file.
 */

module.exports = {
  "Core": {
    "global": {
      "white": {
        "value": "#ffffff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffffff",
          "type": "color"
        },
        "name": "CoreGlobalWhite",
        "attributes": {
          "category": "Core",
          "type": "global",
          "item": "white"
        },
        "path": [
          "Core",
          "global",
          "white"
        ]
      },
      "black": {
        "value": "#000000",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#000000",
          "type": "color"
        },
        "name": "CoreGlobalBlack",
        "attributes": {
          "category": "Core",
          "type": "global",
          "item": "black"
        },
        "path": [
          "Core",
          "global",
          "black"
        ]
      },
      "transparent": {
        "value": "#ffffff00",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffffff00",
          "type": "color"
        },
        "name": "CoreGlobalTransparent",
        "attributes": {
          "category": "Core",
          "type": "global",
          "item": "transparent"
        },
        "path": [
          "Core",
          "global",
          "transparent"
        ]
      }
    },
    "neutral": {
      "100": {
        "value": "#fafafa",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#fafafa",
          "type": "color"
        },
        "name": "CoreNeutral100",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "100"
        },
        "path": [
          "Core",
          "neutral",
          "100"
        ]
      },
      "200": {
        "value": "#f5f5f5",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f5f5f5",
          "type": "color"
        },
        "name": "CoreNeutral200",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "200"
        },
        "path": [
          "Core",
          "neutral",
          "200"
        ]
      },
      "300": {
        "value": "#e5e5e5",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#e5e5e5",
          "type": "color"
        },
        "name": "CoreNeutral300",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "300"
        },
        "path": [
          "Core",
          "neutral",
          "300"
        ]
      },
      "400": {
        "value": "#d4d4d4",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d4d4d4",
          "type": "color"
        },
        "name": "CoreNeutral400",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "400"
        },
        "path": [
          "Core",
          "neutral",
          "400"
        ]
      },
      "500": {
        "value": "#a3a3a3",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#a3a3a3",
          "type": "color"
        },
        "name": "CoreNeutral500",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "500"
        },
        "path": [
          "Core",
          "neutral",
          "500"
        ]
      },
      "600": {
        "value": "#737373",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#737373",
          "type": "color"
        },
        "name": "CoreNeutral600",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "600"
        },
        "path": [
          "Core",
          "neutral",
          "600"
        ]
      },
      "700": {
        "value": "#525252",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#525252",
          "type": "color"
        },
        "name": "CoreNeutral700",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "700"
        },
        "path": [
          "Core",
          "neutral",
          "700"
        ]
      },
      "800": {
        "value": "#404040",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#404040",
          "type": "color"
        },
        "name": "CoreNeutral800",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "800"
        },
        "path": [
          "Core",
          "neutral",
          "800"
        ]
      },
      "900": {
        "value": "#353535",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#353535",
          "type": "color"
        },
        "name": "CoreNeutral900",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "900"
        },
        "path": [
          "Core",
          "neutral",
          "900"
        ]
      },
      "1000": {
        "value": "#171717",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#171717",
          "type": "color"
        },
        "name": "CoreNeutral1000",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "1000"
        },
        "path": [
          "Core",
          "neutral",
          "1000"
        ]
      }
    },
    "primary": {
      "100": {
        "value": "#ffd5b8",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffd5b8",
          "type": "color"
        },
        "name": "CorePrimary100",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "100"
        },
        "path": [
          "Core",
          "primary",
          "100"
        ]
      },
      "200": {
        "value": "#ffb685",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffb685",
          "type": "color"
        },
        "name": "CorePrimary200",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "200"
        },
        "path": [
          "Core",
          "primary",
          "200"
        ]
      },
      "300": {
        "value": "#ff9d57",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ff9d57",
          "type": "color"
        },
        "name": "CorePrimary300",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "300"
        },
        "path": [
          "Core",
          "primary",
          "300"
        ]
      },
      "400": {
        "value": "#bd550a",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#bd550a",
          "type": "color"
        },
        "name": "CorePrimary400",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "400"
        },
        "path": [
          "Core",
          "primary",
          "400"
        ]
      },
      "500": {
        "value": "#8a3900",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#8a3900",
          "type": "color"
        },
        "name": "CorePrimary500",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "500"
        },
        "path": [
          "Core",
          "primary",
          "500"
        ]
      },
      "600": {
        "value": "#572400",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#572400",
          "type": "color"
        },
        "name": "CorePrimary600",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "600"
        },
        "path": [
          "Core",
          "primary",
          "600"
        ]
      },
      "goat": {
        "value": "#ee7620",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ee7620",
          "type": "color"
        },
        "name": "CorePrimaryGoat",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "goat"
        },
        "path": [
          "Core",
          "primary",
          "goat"
        ]
      }
    },
    "secondary": {
      "100": {
        "value": "#ffe2b2",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffe2b2",
          "type": "color"
        },
        "name": "CoreSecondary100",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "100"
        },
        "path": [
          "Core",
          "secondary",
          "100"
        ]
      },
      "200": {
        "value": "#ffcc7a",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffcc7a",
          "type": "color"
        },
        "name": "CoreSecondary200",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "200"
        },
        "path": [
          "Core",
          "secondary",
          "200"
        ]
      },
      "300": {
        "value": "#ffb742",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffb742",
          "type": "color"
        },
        "name": "CoreSecondary300",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "300"
        },
        "path": [
          "Core",
          "secondary",
          "300"
        ]
      },
      "400": {
        "value": "#c27800",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#c27800",
          "type": "color"
        },
        "name": "CoreSecondary400",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "400"
        },
        "path": [
          "Core",
          "secondary",
          "400"
        ]
      },
      "500": {
        "value": "#8f5800",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#8f5800",
          "type": "color"
        },
        "name": "CoreSecondary500",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "500"
        },
        "path": [
          "Core",
          "secondary",
          "500"
        ]
      },
      "600": {
        "value": "#5c3900",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#5c3900",
          "type": "color"
        },
        "name": "CoreSecondary600",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "600"
        },
        "path": [
          "Core",
          "secondary",
          "600"
        ]
      },
      "main": {
        "value": "#f59d0f",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f59d0f",
          "type": "color"
        },
        "name": "CoreSecondaryMain",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "main"
        },
        "path": [
          "Core",
          "secondary",
          "main"
        ]
      }
    },
    "Gradient": {
      "Orange > Amber - #EE7622 > #F59C0D": {
        "value": "linear-gradient(90deg, #ee7622 0%, #f6a705 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #ee7622 0%, #f6a705 100%)",
          "type": "color"
        },
        "name": "CoreGradientOrangeAmberEe7622F59C0D",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Orange > Amber - #EE7622 > #F59C0D"
        },
        "path": [
          "Core",
          "Gradient",
          "Orange > Amber - #EE7622 > #F59C0D"
        ]
      },
      "Orange > Pink - #EE7620 > #F131BC": {
        "value": "linear-gradient(119deg, #ee7620 0%, #f131bc 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(119deg, #ee7620 0%, #f131bc 100%)",
          "type": "color"
        },
        "name": "CoreGradientOrangePinkEe7620F131Bc",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Orange > Pink - #EE7620 > #F131BC"
        },
        "path": [
          "Core",
          "Gradient",
          "Orange > Pink - #EE7620 > #F131BC"
        ]
      },
      "Orange > Pink > Purple - #F79426, #F131BC, #5212E4": {
        "value": "linear-gradient(90deg, #f79426 0%, #f131bc 42.35%, #5212e4 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #f79426 0%, #f131bc 42.35%, #5212e4 100%)",
          "type": "color"
        },
        "name": "CoreGradientOrangePinkPurpleF79426F131Bc5212E4",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Orange > Pink > Purple - #F79426, #F131BC, #5212E4"
        },
        "path": [
          "Core",
          "Gradient",
          "Orange > Pink > Purple - #F79426, #F131BC, #5212E4"
        ]
      },
      "Neutral 6-9 - #737373 > #353535": {
        "value": "linear-gradient(90deg, #737373 0%, #353535 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #737373 0%, #353535 100%)",
          "type": "color"
        },
        "name": "CoreGradientNeutral69737373353535",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Neutral 6-9 - #737373 > #353535"
        },
        "path": [
          "Core",
          "Gradient",
          "Neutral 6-9 - #737373 > #353535"
        ]
      },
      "Dark Grey": {
        "value": "linear-gradient(90deg, #414141 0%, #363636 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #414141 0%, #363636 100%)",
          "type": "color"
        },
        "name": "CoreGradientDarkGrey",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Dark Grey"
        },
        "path": [
          "Core",
          "Gradient",
          "Dark Grey"
        ]
      }
    },
    "success": {
      "100": {
        "value": "#d5fff2",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d5fff2",
          "type": "color"
        },
        "name": "CoreSuccess100",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "100"
        },
        "path": [
          "Core",
          "success",
          "100"
        ]
      },
      "200": {
        "value": "#b5ffe9",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#b5ffe9",
          "type": "color"
        },
        "name": "CoreSuccess200",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "200"
        },
        "path": [
          "Core",
          "success",
          "200"
        ]
      },
      "300": {
        "value": "#95ffdf",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#95ffdf",
          "type": "color"
        },
        "name": "CoreSuccess300",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "300"
        },
        "path": [
          "Core",
          "success",
          "300"
        ]
      },
      "400": {
        "value": "#79e1c2",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#79e1c2",
          "type": "color"
        },
        "name": "CoreSuccess400",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "400"
        },
        "path": [
          "Core",
          "success",
          "400"
        ]
      },
      "500": {
        "value": "#409078",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#409078",
          "type": "color"
        },
        "name": "CoreSuccess500",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "500"
        },
        "path": [
          "Core",
          "success",
          "500"
        ]
      },
      "600": {
        "value": "#296754",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#296754",
          "type": "color"
        },
        "name": "CoreSuccess600",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "600"
        },
        "path": [
          "Core",
          "success",
          "600"
        ]
      },
      "main": {
        "value": "#5bb99c",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#5bb99c",
          "type": "color"
        },
        "name": "CoreSuccessMain",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "main"
        },
        "path": [
          "Core",
          "success",
          "main"
        ]
      }
    },
    "supporting1": {
      "100": {
        "value": "#b7e1ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#b7e1ff",
          "type": "color"
        },
        "name": "CoreSupporting1100",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "100"
        },
        "path": [
          "Core",
          "supporting1",
          "100"
        ]
      },
      "200": {
        "value": "#85ccff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#85ccff",
          "type": "color"
        },
        "name": "CoreSupporting1200",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "200"
        },
        "path": [
          "Core",
          "supporting1",
          "200"
        ]
      },
      "300": {
        "value": "#54b7ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#54b7ff",
          "type": "color"
        },
        "name": "CoreSupporting1300",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "300"
        },
        "path": [
          "Core",
          "supporting1",
          "300"
        ]
      },
      "400": {
        "value": "#0870bb",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#0870bb",
          "type": "color"
        },
        "name": "CoreSupporting1400",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "400"
        },
        "path": [
          "Core",
          "supporting1",
          "400"
        ]
      },
      "500": {
        "value": "#004f88",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#004f88",
          "type": "color"
        },
        "name": "CoreSupporting1500",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "500"
        },
        "path": [
          "Core",
          "supporting1",
          "500"
        ]
      },
      "600": {
        "value": "#003255",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#003255",
          "type": "color"
        },
        "name": "CoreSupporting1600",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "600"
        },
        "path": [
          "Core",
          "supporting1",
          "600"
        ]
      },
      "main": {
        "value": "#2098ee",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#2098ee",
          "type": "color"
        },
        "name": "CoreSupporting1Main",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "main"
        },
        "path": [
          "Core",
          "supporting1",
          "main"
        ]
      }
    },
    "supporting2": {
      "100": {
        "value": "#fdafff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#fdafff",
          "type": "color"
        },
        "name": "CoreSupporting2100",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "100"
        },
        "path": [
          "Core",
          "supporting2",
          "100"
        ]
      },
      "200": {
        "value": "#fc74ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#fc74ff",
          "type": "color"
        },
        "name": "CoreSupporting2200",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "200"
        },
        "path": [
          "Core",
          "supporting2",
          "200"
        ]
      },
      "300": {
        "value": "#cb21cf",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#cb21cf",
          "type": "color"
        },
        "name": "CoreSupporting2300",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "300"
        },
        "path": [
          "Core",
          "supporting2",
          "300"
        ]
      },
      "400": {
        "value": "#a310a6",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#a310a6",
          "type": "color"
        },
        "name": "CoreSupporting2400",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "400"
        },
        "path": [
          "Core",
          "supporting2",
          "400"
        ]
      },
      "500": {
        "value": "#7b047d",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#7b047d",
          "type": "color"
        },
        "name": "CoreSupporting2500",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "500"
        },
        "path": [
          "Core",
          "supporting2",
          "500"
        ]
      },
      "600": {
        "value": "#530054",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#530054",
          "type": "color"
        },
        "name": "CoreSupporting2600",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "600"
        },
        "path": [
          "Core",
          "supporting2",
          "600"
        ]
      },
      "main": {
        "value": "#f437f8",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f437f8",
          "type": "color"
        },
        "name": "CoreSupporting2Main",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "main"
        },
        "path": [
          "Core",
          "supporting2",
          "main"
        ]
      }
    },
    "supporting3": {
      "100": {
        "value": "#d5b7ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d5b7ff",
          "type": "color"
        },
        "name": "CoreSupporting3100",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "100"
        },
        "path": [
          "Core",
          "supporting3",
          "100"
        ]
      },
      "200": {
        "value": "#b885ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#b885ff",
          "type": "color"
        },
        "name": "CoreSupporting3200",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "200"
        },
        "path": [
          "Core",
          "supporting3",
          "200"
        ]
      },
      "300": {
        "value": "#9b54ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#9b54ff",
          "type": "color"
        },
        "name": "CoreSupporting3300",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "300"
        },
        "path": [
          "Core",
          "supporting3",
          "300"
        ]
      },
      "400": {
        "value": "#5308bb",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#5308bb",
          "type": "color"
        },
        "name": "CoreSupporting3400",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "400"
        },
        "path": [
          "Core",
          "supporting3",
          "400"
        ]
      },
      "500": {
        "value": "#390088",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#390088",
          "type": "color"
        },
        "name": "CoreSupporting3500",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "500"
        },
        "path": [
          "Core",
          "supporting3",
          "500"
        ]
      },
      "600": {
        "value": "#240055",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#240055",
          "type": "color"
        },
        "name": "CoreSupporting3600",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "600"
        },
        "path": [
          "Core",
          "supporting3",
          "600"
        ]
      },
      "main": {
        "value": "#7620ee",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#7620ee",
          "type": "color"
        },
        "name": "CoreSupporting3Main",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "main"
        },
        "path": [
          "Core",
          "supporting3",
          "main"
        ]
      }
    },
    "destructive": {
      "100": {
        "value": "#ffafaf",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffafaf",
          "type": "color"
        },
        "name": "CoreDestructive100",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "100"
        },
        "path": [
          "Core",
          "destructive",
          "100"
        ]
      },
      "200": {
        "value": "#ff7474",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ff7474",
          "type": "color"
        },
        "name": "CoreDestructive200",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "200"
        },
        "path": [
          "Core",
          "destructive",
          "200"
        ]
      },
      "300": {
        "value": "#f93737",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f93737",
          "type": "color"
        },
        "name": "CoreDestructive300",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "300"
        },
        "path": [
          "Core",
          "destructive",
          "300"
        ]
      },
      "400": {
        "value": "#a71010",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#a71010",
          "type": "color"
        },
        "name": "CoreDestructive400",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "400"
        },
        "path": [
          "Core",
          "destructive",
          "400"
        ]
      },
      "500": {
        "value": "#7e0404",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#7e0404",
          "type": "color"
        },
        "name": "CoreDestructive500",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "500"
        },
        "path": [
          "Core",
          "destructive",
          "500"
        ]
      },
      "600": {
        "value": "#550000",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#550000",
          "type": "color"
        },
        "name": "CoreDestructive600",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "600"
        },
        "path": [
          "Core",
          "destructive",
          "600"
        ]
      },
      "main": {
        "value": "#d02121",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d02121",
          "type": "color"
        },
        "name": "CoreDestructiveMain",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "main"
        },
        "path": [
          "Core",
          "destructive",
          "main"
        ]
      }
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "Core"
    ]
  }
};