/**
 * // This file is auto-generated by the sd.config.cjs file.
 */

module.exports = {
  "Core": {
    "global": {
      "white": {
        "value": "#ffffff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffffff",
          "type": "color"
        },
        "name": "CoreGlobalWhite",
        "attributes": {
          "category": "Core",
          "type": "global",
          "item": "white"
        },
        "path": [
          "Core",
          "global",
          "white"
        ]
      },
      "black": {
        "value": "#000000",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#000000",
          "type": "color"
        },
        "name": "CoreGlobalBlack",
        "attributes": {
          "category": "Core",
          "type": "global",
          "item": "black"
        },
        "path": [
          "Core",
          "global",
          "black"
        ]
      },
      "transparent": {
        "value": "#ffffff00",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffffff00",
          "type": "color"
        },
        "name": "CoreGlobalTransparent",
        "attributes": {
          "category": "Core",
          "type": "global",
          "item": "transparent"
        },
        "path": [
          "Core",
          "global",
          "transparent"
        ]
      }
    },
    "neutral": {
      "s100": {
        "value": "#fafafa",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#fafafa",
          "type": "color"
        },
        "name": "CoreNeutralS100",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s100"
        },
        "path": [
          "Core",
          "neutral",
          "s100"
        ]
      },
      "s200": {
        "value": "#f5f5f5",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f5f5f5",
          "type": "color"
        },
        "name": "CoreNeutralS200",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s200"
        },
        "path": [
          "Core",
          "neutral",
          "s200"
        ]
      },
      "s300": {
        "value": "#e5e5e5",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#e5e5e5",
          "type": "color"
        },
        "name": "CoreNeutralS300",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s300"
        },
        "path": [
          "Core",
          "neutral",
          "s300"
        ]
      },
      "s400": {
        "value": "#d4d4d4",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d4d4d4",
          "type": "color"
        },
        "name": "CoreNeutralS400",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s400"
        },
        "path": [
          "Core",
          "neutral",
          "s400"
        ]
      },
      "s500": {
        "value": "#a3a3a3",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#a3a3a3",
          "type": "color"
        },
        "name": "CoreNeutralS500",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s500"
        },
        "path": [
          "Core",
          "neutral",
          "s500"
        ]
      },
      "s600": {
        "value": "#737373",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#737373",
          "type": "color"
        },
        "name": "CoreNeutralS600",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s600"
        },
        "path": [
          "Core",
          "neutral",
          "s600"
        ]
      },
      "s700": {
        "value": "#525252",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#525252",
          "type": "color"
        },
        "name": "CoreNeutralS700",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s700"
        },
        "path": [
          "Core",
          "neutral",
          "s700"
        ]
      },
      "s800": {
        "value": "#404040",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#404040",
          "type": "color"
        },
        "name": "CoreNeutralS800",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s800"
        },
        "path": [
          "Core",
          "neutral",
          "s800"
        ]
      },
      "s900": {
        "value": "#353535",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#353535",
          "type": "color"
        },
        "name": "CoreNeutralS900",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s900"
        },
        "path": [
          "Core",
          "neutral",
          "s900"
        ]
      },
      "s1000": {
        "value": "#171717",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#171717",
          "type": "color"
        },
        "name": "CoreNeutralS1000",
        "attributes": {
          "category": "Core",
          "type": "neutral",
          "item": "s1000"
        },
        "path": [
          "Core",
          "neutral",
          "s1000"
        ]
      }
    },
    "primary": {
      "s100": {
        "value": "#ffd5b8",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffd5b8",
          "type": "color"
        },
        "name": "CorePrimaryS100",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "s100"
        },
        "path": [
          "Core",
          "primary",
          "s100"
        ]
      },
      "s200": {
        "value": "#ffb685",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffb685",
          "type": "color"
        },
        "name": "CorePrimaryS200",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "s200"
        },
        "path": [
          "Core",
          "primary",
          "s200"
        ]
      },
      "s300": {
        "value": "#ff9d57",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ff9d57",
          "type": "color"
        },
        "name": "CorePrimaryS300",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "s300"
        },
        "path": [
          "Core",
          "primary",
          "s300"
        ]
      },
      "s400": {
        "value": "#bd550a",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#bd550a",
          "type": "color"
        },
        "name": "CorePrimaryS400",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "s400"
        },
        "path": [
          "Core",
          "primary",
          "s400"
        ]
      },
      "s500": {
        "value": "#8a3900",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#8a3900",
          "type": "color"
        },
        "name": "CorePrimaryS500",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "s500"
        },
        "path": [
          "Core",
          "primary",
          "s500"
        ]
      },
      "s600": {
        "value": "#572400",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#572400",
          "type": "color"
        },
        "name": "CorePrimaryS600",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "s600"
        },
        "path": [
          "Core",
          "primary",
          "s600"
        ]
      },
      "goat": {
        "value": "#ee7620",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ee7620",
          "type": "color"
        },
        "name": "CorePrimaryGoat",
        "attributes": {
          "category": "Core",
          "type": "primary",
          "item": "goat"
        },
        "path": [
          "Core",
          "primary",
          "goat"
        ]
      }
    },
    "secondary": {
      "s100": {
        "value": "#ffe2b2",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffe2b2",
          "type": "color"
        },
        "name": "CoreSecondaryS100",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "s100"
        },
        "path": [
          "Core",
          "secondary",
          "s100"
        ]
      },
      "s200": {
        "value": "#ffcc7a",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffcc7a",
          "type": "color"
        },
        "name": "CoreSecondaryS200",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "s200"
        },
        "path": [
          "Core",
          "secondary",
          "s200"
        ]
      },
      "s300": {
        "value": "#ffb742",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffb742",
          "type": "color"
        },
        "name": "CoreSecondaryS300",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "s300"
        },
        "path": [
          "Core",
          "secondary",
          "s300"
        ]
      },
      "s400": {
        "value": "#c27800",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#c27800",
          "type": "color"
        },
        "name": "CoreSecondaryS400",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "s400"
        },
        "path": [
          "Core",
          "secondary",
          "s400"
        ]
      },
      "s500": {
        "value": "#8f5800",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#8f5800",
          "type": "color"
        },
        "name": "CoreSecondaryS500",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "s500"
        },
        "path": [
          "Core",
          "secondary",
          "s500"
        ]
      },
      "s600": {
        "value": "#5c3900",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#5c3900",
          "type": "color"
        },
        "name": "CoreSecondaryS600",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "s600"
        },
        "path": [
          "Core",
          "secondary",
          "s600"
        ]
      },
      "main": {
        "value": "#f59d0f",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f59d0f",
          "type": "color"
        },
        "name": "CoreSecondaryMain",
        "attributes": {
          "category": "Core",
          "type": "secondary",
          "item": "main"
        },
        "path": [
          "Core",
          "secondary",
          "main"
        ]
      }
    },
    "Gradient": {
      "Orange > Amber - #EE7622 > #F59C0D": {
        "value": "linear-gradient(90deg, #ee7622 0%, #f6a705 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #ee7622 0%, #f6a705 100%)",
          "type": "color"
        },
        "name": "CoreGradientOrangeAmberEe7622F59C0D",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Orange > Amber - #EE7622 > #F59C0D"
        },
        "path": [
          "Core",
          "Gradient",
          "Orange > Amber - #EE7622 > #F59C0D"
        ]
      },
      "Orange > Pink - #EE7620 > #F131BC": {
        "value": "linear-gradient(119deg, #ee7620 0%, #f131bc 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(119deg, #ee7620 0%, #f131bc 100%)",
          "type": "color"
        },
        "name": "CoreGradientOrangePinkEe7620F131Bc",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Orange > Pink - #EE7620 > #F131BC"
        },
        "path": [
          "Core",
          "Gradient",
          "Orange > Pink - #EE7620 > #F131BC"
        ]
      },
      "Orange > Pink > Purple - #F79426, #F131BC, #5212E4": {
        "value": "linear-gradient(90deg, #f79426 0%, #f131bc 42.35%, #5212e4 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #f79426 0%, #f131bc 42.35%, #5212e4 100%)",
          "type": "color"
        },
        "name": "CoreGradientOrangePinkPurpleF79426F131Bc5212E4",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Orange > Pink > Purple - #F79426, #F131BC, #5212E4"
        },
        "path": [
          "Core",
          "Gradient",
          "Orange > Pink > Purple - #F79426, #F131BC, #5212E4"
        ]
      },
      "Neutral 6-9 - #737373 > #353535": {
        "value": "linear-gradient(90deg, #737373 0%, #353535 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #737373 0%, #353535 100%)",
          "type": "color"
        },
        "name": "CoreGradientNeutral69737373353535",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Neutral 6-9 - #737373 > #353535"
        },
        "path": [
          "Core",
          "Gradient",
          "Neutral 6-9 - #737373 > #353535"
        ]
      },
      "Dark Grey": {
        "value": "linear-gradient(90deg, #414141 0%, #363636 100%)",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "linear-gradient(90deg, #414141 0%, #363636 100%)",
          "type": "color"
        },
        "name": "CoreGradientDarkGrey",
        "attributes": {
          "category": "Core",
          "type": "Gradient",
          "item": "Dark Grey"
        },
        "path": [
          "Core",
          "Gradient",
          "Dark Grey"
        ]
      }
    },
    "success": {
      "s100": {
        "value": "#d5fff2",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d5fff2",
          "type": "color"
        },
        "name": "CoreSuccessS100",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "s100"
        },
        "path": [
          "Core",
          "success",
          "s100"
        ]
      },
      "s200": {
        "value": "#b5ffe9",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#b5ffe9",
          "type": "color"
        },
        "name": "CoreSuccessS200",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "s200"
        },
        "path": [
          "Core",
          "success",
          "s200"
        ]
      },
      "s300": {
        "value": "#95ffdf",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#95ffdf",
          "type": "color"
        },
        "name": "CoreSuccessS300",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "s300"
        },
        "path": [
          "Core",
          "success",
          "s300"
        ]
      },
      "s400": {
        "value": "#79e1c2",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#79e1c2",
          "type": "color"
        },
        "name": "CoreSuccessS400",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "s400"
        },
        "path": [
          "Core",
          "success",
          "s400"
        ]
      },
      "s500": {
        "value": "#409078",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#409078",
          "type": "color"
        },
        "name": "CoreSuccessS500",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "s500"
        },
        "path": [
          "Core",
          "success",
          "s500"
        ]
      },
      "s600": {
        "value": "#296754",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#296754",
          "type": "color"
        },
        "name": "CoreSuccessS600",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "s600"
        },
        "path": [
          "Core",
          "success",
          "s600"
        ]
      },
      "main": {
        "value": "#5bb99c",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#5bb99c",
          "type": "color"
        },
        "name": "CoreSuccessMain",
        "attributes": {
          "category": "Core",
          "type": "success",
          "item": "main"
        },
        "path": [
          "Core",
          "success",
          "main"
        ]
      }
    },
    "supporting1": {
      "s100": {
        "value": "#b7e1ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#b7e1ff",
          "type": "color"
        },
        "name": "CoreSupporting1S100",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "s100"
        },
        "path": [
          "Core",
          "supporting1",
          "s100"
        ]
      },
      "s200": {
        "value": "#85ccff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#85ccff",
          "type": "color"
        },
        "name": "CoreSupporting1S200",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "s200"
        },
        "path": [
          "Core",
          "supporting1",
          "s200"
        ]
      },
      "s300": {
        "value": "#54b7ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#54b7ff",
          "type": "color"
        },
        "name": "CoreSupporting1S300",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "s300"
        },
        "path": [
          "Core",
          "supporting1",
          "s300"
        ]
      },
      "s400": {
        "value": "#0870bb",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#0870bb",
          "type": "color"
        },
        "name": "CoreSupporting1S400",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "s400"
        },
        "path": [
          "Core",
          "supporting1",
          "s400"
        ]
      },
      "s500": {
        "value": "#004f88",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#004f88",
          "type": "color"
        },
        "name": "CoreSupporting1S500",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "s500"
        },
        "path": [
          "Core",
          "supporting1",
          "s500"
        ]
      },
      "s600": {
        "value": "#003255",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#003255",
          "type": "color"
        },
        "name": "CoreSupporting1S600",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "s600"
        },
        "path": [
          "Core",
          "supporting1",
          "s600"
        ]
      },
      "main": {
        "value": "#2098ee",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#2098ee",
          "type": "color"
        },
        "name": "CoreSupporting1Main",
        "attributes": {
          "category": "Core",
          "type": "supporting1",
          "item": "main"
        },
        "path": [
          "Core",
          "supporting1",
          "main"
        ]
      }
    },
    "supporting2": {
      "s100": {
        "value": "#fdafff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#fdafff",
          "type": "color"
        },
        "name": "CoreSupporting2S100",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "s100"
        },
        "path": [
          "Core",
          "supporting2",
          "s100"
        ]
      },
      "s200": {
        "value": "#fc74ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#fc74ff",
          "type": "color"
        },
        "name": "CoreSupporting2S200",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "s200"
        },
        "path": [
          "Core",
          "supporting2",
          "s200"
        ]
      },
      "s300": {
        "value": "#cb21cf",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#cb21cf",
          "type": "color"
        },
        "name": "CoreSupporting2S300",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "s300"
        },
        "path": [
          "Core",
          "supporting2",
          "s300"
        ]
      },
      "s400": {
        "value": "#a310a6",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#a310a6",
          "type": "color"
        },
        "name": "CoreSupporting2S400",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "s400"
        },
        "path": [
          "Core",
          "supporting2",
          "s400"
        ]
      },
      "s500": {
        "value": "#7b047d",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#7b047d",
          "type": "color"
        },
        "name": "CoreSupporting2S500",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "s500"
        },
        "path": [
          "Core",
          "supporting2",
          "s500"
        ]
      },
      "s600": {
        "value": "#530054",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#530054",
          "type": "color"
        },
        "name": "CoreSupporting2S600",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "s600"
        },
        "path": [
          "Core",
          "supporting2",
          "s600"
        ]
      },
      "main": {
        "value": "#f437f8",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f437f8",
          "type": "color"
        },
        "name": "CoreSupporting2Main",
        "attributes": {
          "category": "Core",
          "type": "supporting2",
          "item": "main"
        },
        "path": [
          "Core",
          "supporting2",
          "main"
        ]
      }
    },
    "supporting3": {
      "s100": {
        "value": "#d5b7ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d5b7ff",
          "type": "color"
        },
        "name": "CoreSupporting3S100",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "s100"
        },
        "path": [
          "Core",
          "supporting3",
          "s100"
        ]
      },
      "s200": {
        "value": "#b885ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#b885ff",
          "type": "color"
        },
        "name": "CoreSupporting3S200",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "s200"
        },
        "path": [
          "Core",
          "supporting3",
          "s200"
        ]
      },
      "s300": {
        "value": "#9b54ff",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#9b54ff",
          "type": "color"
        },
        "name": "CoreSupporting3S300",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "s300"
        },
        "path": [
          "Core",
          "supporting3",
          "s300"
        ]
      },
      "s400": {
        "value": "#5308bb",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#5308bb",
          "type": "color"
        },
        "name": "CoreSupporting3S400",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "s400"
        },
        "path": [
          "Core",
          "supporting3",
          "s400"
        ]
      },
      "s500": {
        "value": "#390088",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#390088",
          "type": "color"
        },
        "name": "CoreSupporting3S500",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "s500"
        },
        "path": [
          "Core",
          "supporting3",
          "s500"
        ]
      },
      "s600": {
        "value": "#240055",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#240055",
          "type": "color"
        },
        "name": "CoreSupporting3S600",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "s600"
        },
        "path": [
          "Core",
          "supporting3",
          "s600"
        ]
      },
      "main": {
        "value": "#7620ee",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#7620ee",
          "type": "color"
        },
        "name": "CoreSupporting3Main",
        "attributes": {
          "category": "Core",
          "type": "supporting3",
          "item": "main"
        },
        "path": [
          "Core",
          "supporting3",
          "main"
        ]
      }
    },
    "destructive": {
      "s100": {
        "value": "#ffafaf",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ffafaf",
          "type": "color"
        },
        "name": "CoreDestructiveS100",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "s100"
        },
        "path": [
          "Core",
          "destructive",
          "s100"
        ]
      },
      "s200": {
        "value": "#ff7474",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#ff7474",
          "type": "color"
        },
        "name": "CoreDestructiveS200",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "s200"
        },
        "path": [
          "Core",
          "destructive",
          "s200"
        ]
      },
      "s300": {
        "value": "#f93737",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#f93737",
          "type": "color"
        },
        "name": "CoreDestructiveS300",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "s300"
        },
        "path": [
          "Core",
          "destructive",
          "s300"
        ]
      },
      "s400": {
        "value": "#a71010",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#a71010",
          "type": "color"
        },
        "name": "CoreDestructiveS400",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "s400"
        },
        "path": [
          "Core",
          "destructive",
          "s400"
        ]
      },
      "s500": {
        "value": "#7e0404",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#7e0404",
          "type": "color"
        },
        "name": "CoreDestructiveS500",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "s500"
        },
        "path": [
          "Core",
          "destructive",
          "s500"
        ]
      },
      "s600": {
        "value": "#550000",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#550000",
          "type": "color"
        },
        "name": "CoreDestructiveS600",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "s600"
        },
        "path": [
          "Core",
          "destructive",
          "s600"
        ]
      },
      "main": {
        "value": "#d02121",
        "type": "color",
        "filePath": "sd-input/src/from-figma-tokens.json",
        "isSource": true,
        "original": {
          "value": "#d02121",
          "type": "color"
        },
        "name": "CoreDestructiveMain",
        "attributes": {
          "category": "Core",
          "type": "destructive",
          "item": "main"
        },
        "path": [
          "Core",
          "destructive",
          "main"
        ]
      }
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "Core"
    ]
  }
};