name: Create Figma Tokens Pull Request

on:
  push:
    branches:
      - figma-tokens

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'master'
          pr_title: 'Update tokens'
          pr_body: 'This is an automated pull request to update from branch figma-tokens'
          pr_label: 'automated pr'
          github_token: ${{ secrets.FIGMA_PAT }}
