name: Process Fgima Tokens

on:
  pull_request:
jobs:
  process-figma-tokens:
    if: ${{ github.head_ref == 'figma-tokens' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Run token-transformer
        run: npx token-transformer sd-input/src/from-figma-tokens.json sd-input/src/sd-input.json --resolveReferences false

      - name: Run Style-Dictionary
        run: npx style-dictionary build --config sd.config.cjs

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: 'Update tokens'
          add: '.'
